'use client'
import { useMemo, useState } from 'react'
import { useFinanceData } from '@/hooks/use-finance-data'
import { addIncome, deleteIncome, updateIncome, updateProfile } from '@/lib/finance-service'
import { formatMoney, fullMonthLabel, incomeForMonth, isoDate, parseMoney, sameMonth } from '@/lib/finance'
import type { Income, IncomeType } from '@/types/database'
import { Card, ErrorBanner, LoadingState } from '@/components/ui'
import { PageHeader } from '@/components/page-header'
import { EditIcon, PlusIcon, TrashIcon } from '@/components/icons'
import { Modal } from '@/components/modal'
export function IncomesClient(){const {profile,incomes,debts:_,loading,error,refresh}=useFinanceData();const [month,setMonth]=useState(()=>new Date());const [editing,setEditing]=useState<Income|null>(null),[open,setOpen]=useState(false);if(loading)return <LoadingState/>;if(!profile)return <ErrorBanner message={error||'Profil topilmadi.'}/>;const list=incomes.filter(i=>sameMonth(i.income_date,month));const total=incomeForMonth(profile.monthly_salary,incomes,month);return <div className="page"><PageHeader title="Daromadlar" subtitle="Maosh va qo‘shimcha tushumlarni oylar bo‘yicha boshqaring." action={<button className="btn primary" onClick={()=>{setEditing(null);setOpen(true)}}><PlusIcon/>Tushum qo‘shish</button>}/><ErrorBanner message={error}/><div className="month-switch"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><b>{fullMonthLabel(month)}</b><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><Card className="income-summary"><div><span>Bazaviy oylik maosh</span><b>{formatMoney(profile.monthly_salary)}</b><SalaryEditor current={profile.monthly_salary} onSaved={refresh}/></div><div><span>Qo‘shimcha tushumlar</span><b>{formatMoney(list.reduce((s,i)=>s+i.amount,0))}</b><small>{list.length} ta tushum</small></div><div><span>Jami daromad</span><b>{formatMoney(total)}</b><small>{fullMonthLabel(month)}</small></div></Card><Card><div className="card-head"><div><h2>Shu oy tushumlari</h2><p>Bazaviy maosh avtomatik qo‘shiladi.</p></div></div>{list.length===0?<p className="muted pad">Bu oyda qo‘shimcha tushum kiritilmagan.</p>:<div className="table-list">{list.map(i=><div key={i.id} className="table-row"><div className="category-badge">{i.type==='bonus'?'B':i.type==='freelance'?'F':'+'}</div><div><b>{i.title}</b><span>{new Date(`${i.income_date}T00:00:00`).toLocaleDateString('uz-UZ')} · {typeName(i.type)}</span></div><strong>{formatMoney(i.amount)}</strong><div className="row-actions"><button onClick={()=>{setEditing(i);setOpen(true)}}><EditIcon/></button><button className="danger" onClick={async()=>{if(confirm('Tushumni o‘chirasizmi?')){await deleteIncome(i.id);await refresh()}}}><TrashIcon/></button></div></div>)}</div>}</Card>{open&&<Modal title={editing?'Tushumni tahrirlash':'Yangi tushum'} onClose={()=>setOpen(false)}><IncomeForm income={editing||undefined} onCancel={()=>setOpen(false)} onSave={async(data)=>{editing?await updateIncome(editing.id,data):await addIncome(data);setOpen(false);await refresh()}}/></Modal>}</div>}
function typeName(t:IncomeType){return t==='bonus'?'Bonus':t==='freelance'?'Qo‘shimcha ish':t==='salary_extra'?'Qo‘shimcha maosh':'Boshqa'}
function IncomeForm({income,onCancel,onSave}:{income?:Income;onCancel:()=>void;onSave:(x:{title:string;type:IncomeType;amount:number;incomeDate:string;note?:string})=>Promise<void>}){const [title,setTitle]=useState(income?.title??''),[type,setType]=useState<IncomeType>(income?.type??'bonus'),[amount,setAmount]=useState(String(income?.amount??'')),[date,setDate]=useState(income?.income_date??isoDate(new Date())),[note,setNote]=useState(income?.note??''),[busy,setBusy]=useState(false),[err,setErr]=useState('');async function submit(e:React.FormEvent){e.preventDefault();const a=parseMoney(amount);if(!title.trim()||a<=0)return setErr('Nomi va musbat summani kiriting.');setBusy(true);try{await onSave({title:title.trim(),type,amount:a,incomeDate:date,note})}catch(e){setErr(e instanceof Error?e.message:'Xatolik')}finally{setBusy(false)}}return <form className="form-stack" onSubmit={submit}><label><span>Nomi</span><input value={title} onChange={e=>setTitle(e.target.value)} autoFocus/></label><div className="form-grid"><label><span>Turi</span><select value={type} onChange={e=>setType(e.target.value as IncomeType)}><option value="bonus">Bonus</option><option value="freelance">Qo‘shimcha ish</option><option value="salary_extra">Qo‘shimcha maosh</option><option value="other">Boshqa</option></select></label><label><span>Summa</span><input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label><span>Sana</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label><span>Izoh</span><textarea rows={2} value={note} onChange={e=>setNote(e.target.value)}/></label>{err&&<div className="alert alert-danger">{err}</div>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={onCancel}>Bekor</button><button className="btn primary" disabled={busy}>{busy?'Saqlanmoqda…':'Saqlash'}</button></div></form>}
function SalaryEditor({current,onSaved}:{current:number;onSaved:()=>Promise<void>}){const [edit,setEdit]=useState(false),[value,setValue]=useState(String(current)),[busy,setBusy]=useState(false);if(!edit)return <button className="text-btn" onClick={()=>setEdit(true)}>O‘zgartirish</button>;return <div className="inline-edit"><input inputMode="numeric" value={value} onChange={e=>setValue(e.target.value)}/><button disabled={busy} onClick={async()=>{setBusy(true);await updateProfile({monthly_salary:parseMoney(value)});await onSaved();setBusy(false);setEdit(false)}}>Saqlash</button><button onClick={()=>setEdit(false)}>×</button></div>}
