'use client'
import { useMemo, useState } from 'react'
import { useFinanceData } from '@/hooks/use-finance-data'
import { formatMoney, fullMonthLabel, localDate, paymentStatus, paymentsForMonth } from '@/lib/finance'
import { setPaymentPaid } from '@/lib/finance-service'
import { Card, ErrorBanner, LoadingState } from '@/components/ui'
import { PageHeader } from '@/components/page-header'
import { CheckIcon } from '@/components/icons'
export function PaymentsClient(){const {debts,loading,error,refresh}=useFinanceData();const [month,setMonth]=useState(()=>new Date());const [busy,setBusy]=useState('');const payments=useMemo(()=>paymentsForMonth(debts,month),[debts,month]);if(loading)return <LoadingState/>;const paid=payments.filter(p=>p.paid_at).reduce((s,p)=>s+p.amount,0),remaining=payments.filter(p=>!p.paid_at).reduce((s,p)=>s+p.amount,0);const debtById=new Map(debts.map(d=>[d.id,d]));return <div className="page"><PageHeader title="To‘lovlar" subtitle="Oyma-oy majburiyatlar, muddatlar va to‘langan holati."/><ErrorBanner message={error}/><div className="month-switch"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><b>{fullMonthLabel(month)}</b><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><Card className="payment-summary"><div><span>Shu oy reja</span><b>{formatMoney(paid+remaining)}</b></div><div><span>To‘langan</span><b className="good-text">{formatMoney(paid)}</b></div><div><span>Qolgan</span><b>{formatMoney(remaining)}</b></div></Card><div className="payments-layout"><Card><div className="card-head"><div><h2>To‘lovlar ro‘yxati</h2><p>{payments.length} ta rejalashtirilgan to‘lov</p></div></div>{payments.length===0?<p className="muted pad">Bu oy uchun to‘lov rejalashtirilmagan.</p>:<div className="payment-cards">{payments.map(p=>{const debt=debtById.get(p.debt_id),status=paymentStatus(p);return <div key={p.id} className="payment-card"><div className="payment-icon">{debt?.name.slice(0,1).toUpperCase()||'Q'}</div><div className="payment-info"><b>{debt?.name||'Qarz'}</b><span>{new Date(`${p.due_date}T00:00:00`).toLocaleDateString('uz-UZ')} · {debt?.creditor||''}</span></div><strong>{formatMoney(p.amount)}</strong><span className={`status status-${status}`}>{p.paid_at?'To‘langan':status==='overdue'?'Kechikkan':status==='today'?'Bugun':status==='tomorrow'?'Ertaga':'Kutilmoqda'}</span><button className={`pay-check ${p.paid_at?'done':''}`} disabled={busy===p.id} onClick={async()=>{setBusy(p.id);try{await setPaymentPaid(p.id,!p.paid_at);await refresh()}finally{setBusy('')}}}>{p.paid_at?<><CheckIcon/> To‘landi</>:'To‘landi ✓'}</button></div>})}</div>}</Card><Card><div className="card-head"><div><h2>Kalendar</h2><p>To‘lov kunlari</p></div></div><MiniCalendar month={month} dates={payments.map(p=>({date:localDate(p.due_date),paid:Boolean(p.paid_at)}))}/></Card></div></div>}
function MiniCalendar({month,dates}:{month:Date;dates:{date:Date;paid:boolean}[]}){const first=new Date(month.getFullYear(),month.getMonth(),1),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),offset=(first.getDay()+6)%7,cells=[...Array(offset).fill(null),...Array.from({length:days},(_,i)=>i+1)];return <div className="calendar"><div className="calendar-week"><span>Du</span><span>Se</span><span>Cho</span><span>Pa</span><span>Ju</span><span>Sha</span><span>Ya</span></div><div className="calendar-grid">{cells.map((day,i)=>{if(!day)return <span key={`e${i}`}/>;const hits=dates.filter(x=>x.date.getDate()===day);return <div key={day} className={hits.length?'has-payment':''}><b>{day}</b>{hits.length>0&&<i className={hits.every(x=>x.paid)?'paid-dot':'due-dot'}/>}</div>})}</div><div className="calendar-legend"><span><i className="due-dot"/>To‘lov</span><span><i className="paid-dot"/>To‘langan</span></div></div>}
