'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { useFinanceData } from '@/hooks/use-finance-data'
import { updateProfile } from '@/lib/finance-service'
import { createClient } from '@/lib/supabase/client'
import { Card, ErrorBanner, LoadingState } from '@/components/ui'
import { PageHeader } from '@/components/page-header'
export function SettingsClient(){const {profile,loading,error,refresh}=useFinanceData(),router=useRouter();const [name,setName]=useState(''),[enabled,setEnabled]=useState(true),[days,setDays]=useState(1),[hour,setHour]=useState(9),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');useEffect(()=>{if(profile){setName(profile.full_name);setEnabled(profile.reminder_enabled);setDays(profile.reminder_days_before);setHour(profile.reminder_hour)}},[profile]);if(loading)return <LoadingState/>;if(!profile)return <ErrorBanner message={error||'Profil topilmadi.'}/>;async function save(){setBusy(true);setMsg('');try{await updateProfile({full_name:name.trim(),reminder_enabled:enabled,reminder_days_before:days,reminder_hour:hour,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Tashkent'});await refresh();setMsg('Sozlamalar saqlandi.')}finally{setBusy(false)}}return <div className="page"><PageHeader title="Sozlamalar" subtitle="Profil, valyuta va eslatma parametrlarini boshqaring."/><ErrorBanner message={error}/>{msg&&<div className="alert alert-success">{msg}</div>}<div className="settings-grid"><Card><div className="card-head"><div><h2>Profil</h2><p>Akkauntda ko‘rinadigan ism.</p></div></div><label><span>Ism</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Valyuta</span><select value={profile.currency} disabled><option>UZS</option></select><small>Hozirgi versiya UZS uchun optimallashtirilgan.</small></label></Card><Card><div className="card-head"><div><h2>Eslatmalar</h2><p>Yaqin to‘lovlarni interfeysda ajratish.</p></div></div><label className="toggle-label"><span><b>Eslatmalar yoqilsin</b><small>Web Push keyingi bosqichda ulanadi.</small></span><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label><div className="form-grid"><label><span>Necha kun oldin</span><input type="number" min="0" max="30" value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label><span>Soat</span><input type="number" min="0" max="23" value={hour} onChange={e=>setHour(Number(e.target.value))}/></label></div></Card></div><button className="btn primary" disabled={busy} onClick={save}>{busy?'Saqlanmoqda…':'Sozlamalarni saqlash'}</button><Card className="danger-zone"><div><h2>Akkaunt</h2><p>Joriy sessiyadan chiqish.</p></div><button className="btn secondary" onClick={async()=>{await createClient().auth.signOut();router.replace('/login');router.refresh()}}>Akkauntdan chiqish</button></Card></div>}
